In [1]:
#using MNIST dataset from keras
from keras.datasets import mnist
(xtrain,ytrain), (xtest, ytest) = mnist.load_data()

In [2]:
import matplotlib.pyplot as plt
plt.imshow(xtrain[0])
#xtrain[0].shape

In [3]:
#Preprocessing
#reshape
xtrain = xtrain.reshape(60000,28,28,1)
xtest = xtest.reshape(10000,28,28,1)
#one-hot encoding
from keras.utils import to_categorical
ytrain = to_categorical(ytrain)
ytest = to_categorical(ytest)
ytrain[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [4]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
cnn = Sequential()
cnn.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
cnn.add(Conv2D(32, kernel_size=3, activation='relu'))
cnn.add(Flatten())
cnn.add(Dense(10, activation='softmax'))

In [5]:
cnn.compile(optimizer='adam',
            loss='categorical_crossentropy',#as it is multiclass classification
            metrics=['accuracy'])

In [6]:
cnn.fit(xtrain, ytrain, validation_data=(xtest, ytest), epochs=2)

Epoch 1/2
1875/1875 [==============================] - 69s 37ms/step - loss: 0.2718 - accuracy: 0.9510 - val_loss: 0.0986 - val_accuracy: 0.9695
Epoch 2/2
1875/1875 [==============================] - 67s 36ms/step - loss: 0.0727 - accuracy: 0.9780 - val_loss: 0.0820 - val_accuracy: 0.9753


In [10]:
cnn.predict(xtest[:3])#prediction that first three imgs are that of 7,2,1

1/1 [==============================] - 0s 28ms/step


array([[1.3836278e-07, 6.8950720e-11, 4.7430510e-07, 1.2690467e-03,
        4.0598663e-10, 2.2480113e-09, 8.1957358e-12, 9.9870157e-01,
        2.8368251e-05, 3.8592773e-07],
       [6.4119777e-06, 6.1239034e-06, 9.9998593e-01, 3.7958543e-07,
        4.6377185e-08, 2.9752559e-10, 1.0335910e-06, 4.9432286e-10,
        4.6948664e-08, 6.8248316e-15],
       [2.7711171e-04, 9.9793148e-01, 9.5382333e-05, 1.9715860e-06,
        4.5263852e-04, 8.9433262e-05, 7.4306040e-06, 6.5338891e-06,
        1.1365637e-03, 1.4288859e-06]], dtype=float32)

In [11]:
ytest[:3]#model correctly classifies as 7,2,1 as well

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)